on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*' # Push events to matching *, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: julia-actions/setup-julia@v1
        with:
          version: 1.5.3
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Build Project
        run: julia -e 'using Pkg; pkg"add BinaryProvider"; pkg"add BinaryBuilder"; pkg"add SHA"; Pkg.build()'
      - name: Build Release Products
        run: julia build_tarballs.jl
        env:
          BINARYBUILDER_DOWNLOADS_CACHE: "downloads"
          BINARYBUILDER_AUTOMATIC_APPLE: "true"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: Release ${{ steps.get_version.outputs.VERSION }}
          body: Created a new release ${{ steps.get_version.outputs.VERSION }}.
          draft: false
          prerelease: false
      - name: Upload Release Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag_name="${{ steps.get_version.outputs.VERSION }}"
          hub release edit $(find ./products -type f -name "*" -printf "-a %p ") -m "" "$tag_name"
